# Generated by Django 4.2.6 on 2023-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='식당 이름을 입력하세요.', max_length=100)),
                ('location', models.CharField(help_text='식당은 어디에 있나요?', max_length=100)),
                ('cuisine', models.CharField(help_text='어떤 종류의 음식인가요?', max_length=100)),
                ('website', models.URLField(blank=True, help_text='식당과 관련 있는 웹사이트 주소를 입력하세요.', null=True)),
                ('description', models.TextField(help_text='식당을 추천하는 이유를 작성해 주세요.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
