# Generated by Django 4.0.3 on 2024-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='etc', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
